const fs = require('fs');
const path = require('path');

const POSITIVE_WORDS = ['good', 'great', 'best', 'smart', 'wise', 'loyal', 'brave', 'love', 'win', 'victory', 'legacy', 'family', 'honor', 'respect', 'lion', 'strong', 'admire', 'justice', 'right', 'true'];
const NEGATIVE_WORDS = ['bad', 'fool', 'stupid', 'coward', 'traitor', 'hate', 'kill', 'murder', 'weak', 'clumsy', 'whore', 'scum', 'fail', 'defeat', 'stunted', 'insolent', 'arrogant', 'bastard', 'rat', 'shame'];

function getSentiment(text) {
    const tokens = text.toLowerCase().match(/\b\w+\b/g) || [];
    let score = 0;
    for (const token of tokens) {
        if (POSITIVE_WORDS.includes(token)) score += 1;
        if (NEGATIVE_WORDS.includes(token)) score -= 1;
    }
    if (score > 0) return 'positive';
    if (score < 0) return 'negative';
    return 'neutral';
}

const csvPath = 'n:/tywin-bot/lion-tywin-bot/tywin_sorted.csv';
const content = fs.readFileSync(csvPath, 'utf8');
const lines = content.split('\n');
const header = lines[0];
const dataLines = lines.slice(1);

const categories = {
    positive: [],
    negative: [],
    neutral: []
};

for (const line of dataLines) {
    if (!line.trim()) continue;
    const lastCommaIndex = line.lastIndexOf(',');
    if (lastCommaIndex === -1) continue;
    let quote = line.substring(0, lastCommaIndex).trim();
    
    if (quote.startsWith('"') && quote.endsWith('"')) {
        quote = quote.substring(1, quote.length - 1);
    }
    quote = quote.replace(/""/g, '"');

    const sentiment = getSentiment(quote);
    categories[sentiment].push(quote);
}

const output = 
`// This file is automatically generated from tywin_sorted.csv
const QUOTES_POSITIVE = ${JSON.stringify(categories.positive, null, 2)};

const QUOTES_NEGATIVE = ${JSON.stringify(categories.negative, null, 2)};

const QUOTES_NEUTRAL = ${JSON.stringify(categories.neutral, null, 2)};

export const ALL_QUOTES = [...QUOTES_POSITIVE, ...QUOTES_NEGATIVE, ...QUOTES_NEUTRAL];

export const QUOTE_BUCKETS = {
  positive: QUOTES_POSITIVE,
  negative: QUOTES_NEGATIVE,
  neutral: QUOTES_NEUTRAL,
};

export const TYWIN_QUOTES = ALL_QUOTES;
`;

fs.writeFileSync('n:/tywin-bot/lion-tywin-bot/src/server/core/quotes.ts', output);
console.log(`Successfully restored ${dataLines.filter(l => l.trim()).length} quotes.`);
console.log(`Positive: ${categories.positive.length}, Negative: ${categories.negative.length}, Neutral: ${categories.neutral.length}`);
